### Subarrays as no-copy views

One important–and extremely useful–thing to know about array slices is that they return *views* rather than *copies* of the array data.
This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.
Consider our two-dimensional array from before:

In [31]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Let's extract a $2 \times 2$ subarray from this:

In [32]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [33]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [34]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

### Creating copies of arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the ``copy()`` method:

In [35]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


If we now modify this subarray, the original array is not touched:

In [36]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [37]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


#     ESERCIZIO

Creare un array es3 di valori casuali interi (randint) di dimensione 3x3, con
valore massimo (incluso) uguale a 20

In [30]:
import numpy as np
np.random.seed(0)
es3= np.random.randint(21,size=(3,3))
es3

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18]])


1. estrarre il subarray formato dalla seconda riga (es3_sub) come vista e visualizzarlo
2. moltiplicare per 3 tutti gli elementi della seconda colonna di es3
3. visualizzare es3-sub. È cambiato rispetto a prima?
4. estrarre il subarray formato dalla terza colonna di es3 come copia (es3-sub-copy)
5. sommare 10 a tutti gli elementi di es3-sub-copy e visualizzare
6. visualizzare es3. Contiene la modifica del punto 5?

In [31]:
#punto1 (utilizzo 1 perchè voglio i valori della seconda riga, e : perchè voglio tutte le colonne)
es3_sub= es3 [1,:]
es3_sub

array([3, 3, 7])

In [32]:
#punto2 
#prima visualizzo tutti gli elementi della seconda colonna di es3
print("valori della colonna prima della moltiplicazione:", es3[:,1])

valori della colonna prima della moltiplicazione: [15  3 19]


In [33]:
#punto2
#creo prima una variabile per facilitare la moltiplicazione, poi visualizzo il risultato
es3[:,1]=es3[:,1]*3
print("valori della colonna dopo la moltiplicazione:",es3[:,1])

valori della colonna dopo la moltiplicazione: [45  9 57]


In [35]:
#punto3
es3_sub
#è cambiato?si

array([3, 9, 7])

In [37]:
#punto4
es3_sub_copy=es3[:,2].copy()
es3_sub_copy

array([ 0,  7, 18])

In [38]:
#punto5
es3_sub_copy= es3_sub_copy+10
es3_sub_copy

array([10, 17, 28])

In [39]:
#punto6 
#contiene la modifica del punto 5?
es3

array([[12, 45,  0],
       [ 3,  9,  7],
       [ 9, 57, 18]])

In [40]:
#NO NON CONTIENE LA MODIFICA, PERCHE' E' UNA COPIA, NON UNA VISTA