## Creating Arrays from Scratch

Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into NumPy.
Here are several examples:


In [2]:
import numpy as np

In [3]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [14]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [15]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [17]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[ 0.99844933,  0.52183819,  0.22421193],
       [ 0.08007488,  0.45429293,  0.20941444],
       [ 0.14360941,  0.96910973,  0.946117  ]])

In [18]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 1.51772646,  0.39614948, -0.10634696],
       [ 0.25671348,  0.00732722,  0.37783601],
       [ 0.68446945,  0.15926039, -0.70744073]])

In [19]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[2, 3, 4],
       [5, 7, 8],
       [0, 5, 0]])

In [20]:
# Create a 3x3 identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [21]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([ 1.,  1.,  1.])

# ESERCIZIO

* creare lista di 50 elementi

In [4]:
np.zeros(50, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

* creare matrice 2x5, di numeri interi

In [6]:
np.ones((2,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

* creare matrice 3x3 con valori 12.34

In [8]:
np.full((3,3), 12.34)

array([[12.34, 12.34, 12.34],
       [12.34, 12.34, 12.34],
       [12.34, 12.34, 12.34]])

* creare lista di 10 elementi, che inizia da 6 e incrementa di 4 

In [11]:
np.arange(6,10,4)

array([6])

* creare lista di elementi tra 0 e 100 distanziati di 5 

In [14]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

* creare matrice 1x10 di valori casuali tra 0 e 1

In [26]:
np.random.random((1, 10))

array([[0.21918428, 0.44324409, 0.80328254, 0.86550812, 0.79445416,
        0.48544097, 0.80526336, 0.43882371, 0.31855667, 0.49022879]])

 * creare matrice 2x10 di valori con distribuzione
gaussiana con media 0 e deviazione standard 1

In [27]:
np.random.normal(0, 1, (2, 10))

array([[-1.40029716, -0.95024259, -0.59523848,  1.44937529,  0.01429178,
         0.30787485, -1.37316681,  0.12549613, -0.47185709, -0.57421934],
       [-2.32766889, -0.5742118 , -0.26016541, -0.23390004, -0.57609663,
        -1.48422486, -0.72609307, -1.70017838, -0.27139364,  1.72459648]])