## Array Slicing: Accessing Subarrays
# One-dimensional subarrays

In [2]:
import numpy as np

x= np.arange (10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x[:5] #seleziono i primi 5 elementi

array([0, 1, 2, 3, 4])

In [5]:
x[5:] #seleziono gli elementi dopo il 5

array([5, 6, 7, 8, 9])

In [6]:
x[4:7] #seleziono gli elementi che stanno tra 4 e 7 (sub-array centrale)

array([4, 5, 6])

In [7]:
x[::2] #ogni altro elemento

array([0, 2, 4, 6, 8])

In [8]:
x[1::2] #ogni altro elemento a partire dall'indice 1

array([1, 3, 5, 7, 9])

il segno meno INVERTE i valori

In [9]:
x[::-1] #tutti gli elementi invertiti

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [10]:
x[5:: - 2] #inverto a  vicenda dall'indice 5

array([5, 3, 1])

## ESERCIZIO 

* Cambiare l’array creandone uno sempre di 10 valori ma che parta da 5 fino a
15 (incluso o escluso?)

In [13]:
import numpy as np

es1= np.arange(5,16)
es1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Rifare gli esempi delle celle modificati come:
1. primi sei valori
2. elementi dopo l’indice 3
3. elementi dopo il terzo elemento
4. subarray con valori 8,9,10,11,12
5. un elemento ogni tre, partendo dal primo
6. un elemento ogni tre partendo dal terzo elemento

In [15]:
#punto1
es1[:6]

array([ 5,  6,  7,  8,  9, 10])

In [28]:
#punto2
print("elementi dopo l'indice 3:", es1[3])
print("elementi dopo quelli di indice 3:" , es1[4:])

elementi dopo l'indice 3: 8
elementi dopo quelli di indice 3: [ 9 10 11 12 13 14 15]


In [30]:
#punto3
es1[3:]

array([ 8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
#punto4
es1[3:8]

array([ 8,  9, 10, 11, 12])

In [33]:
#punto5
es1[::3]

array([ 5,  8, 11, 14])

In [35]:
#punto6
es1[1::3]

array([ 6,  9, 12, 15])

## Array Slicing: Accessing Subarrays

### Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [24]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [25]:
x2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [26]:
x2[:3, ::2]  # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

Finally, subarray dimensions can even be reversed together:

In [27]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

#### Accessing array rows and columns

One commonly needed routine is accessing of single rows or columns of an array.
This can be done by combining indexing and slicing, using an empty slice marked by a single colon (``:``):

In [28]:
print(x2[:, 0])  # first column of x2

[12  7  1]


In [29]:
print(x2[0, :])  # first row of x2

[12  5  2  4]


In the case of row access, the empty slice can be omitted for a more compact syntax:

In [30]:
print(x2[0])  # equivalent to x2[0, :]

[12  5  2  4]


# ESERCIZIO1

In [38]:
import numpy as np
np.random.seed(0)   #serve per la riproducibilità
#Creare un array es2a di valori casuali interi (randint) di dimensione 4x6, con valore massimo (incluso) uguale a 15.
es2a= np.random.randint(16, size=(4, 6))
es2a


array([[12, 15,  5,  0,  3, 11],
       [ 3,  7,  9,  3,  5,  2],
       [ 4,  7,  6,  8,  8, 12],
       [10,  1,  6,  7,  7, 14]])

* da svolgere
1. prime tre righe, prime tre colonne
2. seconda e terza riga, quarta, quinta e sesta colonna
3. elementi dopo il terzo elemento (elementi dopo la terza riga e la terza colonna)
4. invertire l’ordine delle sole righe; invertire l’ordine delle sole colonne

In [39]:
#punto1
es2a[:,:]

array([[12, 15,  5,  0,  3, 11],
       [ 3,  7,  9,  3,  5,  2],
       [ 4,  7,  6,  8,  8, 12],
       [10,  1,  6,  7,  7, 14]])

In [41]:
#punto1 
es2a[:3,:3]

array([[12, 15,  5],
       [ 3,  7,  9],
       [ 4,  7,  6]])

In [47]:
#punto2 selezionare seconda e terza riga (con l'1 davanti ai due punti stiamo escludendo la prima riga), 
#selezionare la quarta,quinta,sesta colonna (metto 3 perchè la quarta colonna è inclusa)
es2a[1:3,3:6]


array([[ 3,  5,  2],
       [ 8,  8, 12]])

In [48]:
#punto3
es2a[3:,3:]

array([[ 7,  7, 14]])

In [49]:
#punto4 (utilizzo "\n" per ordinare la tabella senò mi verrebbe attaccato)
print("array non invertito: \n",es2a, "\n")

array non invertito: 
 [[12 15  5  0  3 11]
 [ 3  7  9  3  5  2]
 [ 4  7  6  8  8 12]
 [10  1  6  7  7 14]] 



In [53]:
#punto4 inverto solo le righe
print("array inverto solo le righe: \n", es2a[::-1,:], "\n")

array inverto solo le righe: 
 [[10  1  6  7  7 14]
 [ 4  7  6  8  8 12]
 [ 3  7  9  3  5  2]
 [12 15  5  0  3 11]] 



In [55]:
#punto4 inverto solo le colonne
print("array inverto solo le colonne: \n", es2a[:,::-1], "\n")

array inverto solo le colonne: 
 [[11  3  0  5 15 12]
 [ 2  5  3  9  7  3]
 [12  8  8  6  7  4]
 [14  7  7  6  1 10]] 



## ESERCIZIO 2 
Creare un array es2b di valori casuali interi (randint) composto da 2 subarray di dimensione 5x5,con valore massimo (incluso) uguale a 30.

In [58]:
import numpy as np
np.random.seed(0)

es2b= np.random.randint(31, size=(2,5,5))
es2b

array([[[12, 15, 21,  0,  3],
        [27,  3,  7,  9, 19],
        [21, 18,  4, 23,  6],
        [24, 24, 12, 26,  1],
        [ 6,  7, 23, 14, 24]],

       [[17,  5, 25, 13,  8],
        [ 9, 20, 19, 16, 19],
        [ 5, 30, 15, 15,  0],
        [18,  3, 24, 17, 19],
        [29, 19, 19, 14,  7]]])

1. selezionare il primo subarray, da quello le prime 2 righe e le colonne dalla seconda alla quarta

In [61]:
#punto1  per capire il meccanismo (il primo : indica il subarrey, il secondo: indica le righe, il terzo: le colonne)
es2b[:,:,:]

array([[[12, 15, 21,  0,  3],
        [27,  3,  7,  9, 19],
        [21, 18,  4, 23,  6],
        [24, 24, 12, 26,  1],
        [ 6,  7, 23, 14, 24]],

       [[17,  5, 25, 13,  8],
        [ 9, 20, 19, 16, 19],
        [ 5, 30, 15, 15,  0],
        [18,  3, 24, 17, 19],
        [29, 19, 19, 14,  7]]])

In [67]:
#punto1 (sarebbe es2b 0:1,0:2,1:4)
es2b[:1,:2,1:4]

array([[[15, 21,  0],
        [ 3,  7,  9]]])

2. selezionare da entrambi i subarray le prime due righe e prime due colonne e
invertire righe e colonne

In [85]:
#punto2 #selezionato di entrambi i subarray le prime due righe e lle prime due colonne
#salvo nella variabile a per rendere più semplici i passaggi
a= es2b[:,:2,:2,]
a

array([[[12, 15],
        [27,  3]],

       [[17,  5],
        [ 9, 20]]])

In [86]:
#punto 2 invertire righe e colonne
print("subarray 2x2 non invertito \n",a, "\n")

subarray 2x2 non invertito 
 [[[12 15]
  [27  3]]

 [[17  5]
  [ 9 20]]] 



In [87]:
#inverto le righe
print("inverto le righe: \n",a[:,::-1,:], "\n")

inverto le righe: 
 [[[27  3]
  [12 15]]

 [[ 9 20]
  [17  5]]] 



In [89]:
#inverto le colonne
print("inverto le colonne: \n", a[:,:,::-1],"\n")

inverto le colonne: 
 [[[15 12]
  [ 3 27]]

 [[ 5 17]
  [20  9]]] 



In [90]:
#inverto sia le righe che le colonne
print("inverto sia le righe che le colonne: \n", a[:,::-1,::-1], "\n")

inverto sia le righe che le colonne: 
 [[[ 3 27]
  [15 12]]

 [[20  9]
  [ 5 17]]] 

