# ESERCIZIO #


cambiare l'array creandone uno sempre di 10 valori ma che parta da 5 fino a 15

In [2]:
import numpy as np
es1=np.arange(5,15)
es1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

rifare gli esempi delle celle modificati come:
* primi sei valori
* elementi dopo l'indice tre 
* elementi dopo il terzo elemento 
* subarrey con valori 8,9,10,11,12 
* un elemento ogni tre,partendo dal primo
* un elemento ogni tre partendo dal terzo elemento 

In [3]:
# punto 1
es1[:6]

array([ 5,  6,  7,  8,  9, 10])

In [4]:
#punto 2
print("elementi dopo l'indice tre:", es1[3]),
print("elementi dopo l'indice tre:", es1[4:])

elementi dopo l'indice tre: 8
elementi dopo l'indice tre: [ 9 10 11 12 13 14]


In [5]:
#punto3
es1[3:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [6]:
#punto4
es1[3:8]

array([ 8,  9, 10, 11, 12])

In [7]:
#punto5
es1[::2]

array([ 5,  7,  9, 11, 13])

In [8]:
#punto6
es1[2::3]

array([ 7, 10, 13])