## Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### One-dimensional subarrays

In [16]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [18]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [19]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [20]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [21]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

A potentially confusing case is when the ``step`` value is negative.
In this case, the defaults for ``start`` and ``stop`` are swapped.
This becomes a convenient way to reverse an array:

In [22]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [23]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

# ESERCIZIO #


cambiare l'array creandone uno sempre di 10 valori ma che parta da 5 fino a 15

In [2]:
import numpy as np
es1=np.arange(5,15)
es1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

rifare gli esempi delle celle modificati come:
* primi sei valori
* elementi dopo l'indice tre 
* elementi dopo il terzo elemento 
* subarrey con valori 8,9,10,11,12 
* un elemento ogni tre,partendo dal primo
* un elemento ogni tre partendo dal terzo elemento 

In [3]:
# punto 1
es1[:6]

array([ 5,  6,  7,  8,  9, 10])

In [4]:
#punto 2
print("elementi dopo l'indice tre:", es1[3]),
print("elementi dopo l'indice tre:", es1[4:])

elementi dopo l'indice tre: 8
elementi dopo l'indice tre: [ 9 10 11 12 13 14]


In [5]:
#punto3
es1[3:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [6]:
#punto4
es1[3:8]

array([ 8,  9, 10, 11, 12])

In [7]:
#punto5
es1[::2]

array([ 5,  7,  9, 11, 13])

In [8]:
#punto6
es1[2::3]

array([ 7, 10, 13])